//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButterPayroll.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class InsuranceRates : global::System.Configuration.ApplicationSettingsBase {
        
        private static InsuranceRates defaultInstance = ((InsuranceRates)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InsuranceRates())));
        
        public static InsuranceRates Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("407")]
        public string Medicare_A {
            get {
                return ((string)(this["Medicare_A"]));
            }
            set {
                this["Medicare_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104.9")]
        public string Medicare_B {
            get {
                return ((string)(this["Medicare_B"]));
            }
            set {
                this["Medicare_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("511.9")]
        public string Medicare_AB {
            get {
                return ((string)(this["Medicare_AB"]));
            }
            set {
                this["Medicare_AB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public string BlueCross_HMO_I {
            get {
                return ((string)(this["BlueCross_HMO_I"]));
            }
            set {
                this["BlueCross_HMO_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("162")]
        public string BlueCross_HMO_F {
            get {
                return ((string)(this["BlueCross_HMO_F"]));
            }
            set {
                this["BlueCross_HMO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BlueCross_POS_I {
            get {
                return ((string)(this["BlueCross_POS_I"]));
            }
            set {
                this["BlueCross_POS_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BlueCross_POS_F {
            get {
                return ((string)(this["BlueCross_POS_F"]));
            }
            set {
                this["BlueCross_POS_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("253")]
        public string BlueCross_PPO_F {
            get {
                return ((string)(this["BlueCross_PPO_F"]));
            }
            set {
                this["BlueCross_PPO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string HIP_HMO_I {
            get {
                return ((string)(this["HIP_HMO_I"]));
            }
            set {
                this["HIP_HMO_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public string HIP_HMO_F {
            get {
                return ((string)(this["HIP_HMO_F"]));
            }
            set {
                this["HIP_HMO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public string HIP_POS_I {
            get {
                return ((string)(this["HIP_POS_I"]));
            }
            set {
                this["HIP_POS_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308")]
        public string HIP_POS_F {
            get {
                return ((string)(this["HIP_POS_F"]));
            }
            set {
                this["HIP_POS_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209")]
        public string HIP_PPO_I {
            get {
                return ((string)(this["HIP_PPO_I"]));
            }
            set {
                this["HIP_PPO_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("628")]
        public string HIP_PPO_F {
            get {
                return ((string)(this["HIP_PPO_F"]));
            }
            set {
                this["HIP_PPO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43")]
        public string Aetna_HMO_I {
            get {
                return ((string)(this["Aetna_HMO_I"]));
            }
            set {
                this["Aetna_HMO_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public string Aetna_HMO_F {
            get {
                return ((string)(this["Aetna_HMO_F"]));
            }
            set {
                this["Aetna_HMO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97")]
        public string Aetna_POS_I {
            get {
                return ((string)(this["Aetna_POS_I"]));
            }
            set {
                this["Aetna_POS_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237")]
        public string Aetna_POS_F {
            get {
                return ((string)(this["Aetna_POS_F"]));
            }
            set {
                this["Aetna_POS_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("198")]
        public string Aetna_PPO_I {
            get {
                return ((string)(this["Aetna_PPO_I"]));
            }
            set {
                this["Aetna_PPO_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("603")]
        public string Aetna_PPO_F {
            get {
                return ((string)(this["Aetna_PPO_F"]));
            }
            set {
                this["Aetna_PPO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string Dental_I {
            get {
                return ((string)(this["Dental_I"]));
            }
            set {
                this["Dental_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public string Dental_F {
            get {
                return ((string)(this["Dental_F"]));
            }
            set {
                this["Dental_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public string Optical_I {
            get {
                return ((string)(this["Optical_I"]));
            }
            set {
                this["Optical_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49")]
        public string Optical_F {
            get {
                return ((string)(this["Optical_F"]));
            }
            set {
                this["Optical_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BlueCross_PPO_I {
            get {
                return ((string)(this["BlueCross_PPO_I"]));
            }
            set {
                this["BlueCross_PPO_I"] = value;
            }
        }
    }
}
